# config.yaml

# Data configuration
data:
  train_locations: 
    - "pondinlet"
    - "tuq"
  validation_regions:
    - 4
    - 13
  evaluation_patch_ids: ["01851", "01857", "01924",  "02015", "02035", "02047","05510","05511"]
  s2_dirs: 
    - "/cs/student/projects2/aisd/2024/tcannon/dissertation/Dissertation/input_data/s2_patches_pondinlet"
    - "/cs/student/projects2/aisd/2024/tcannon/dissertation/Dissertation/input_data/s2_patches_tuk"
  lidar_dirs: 
    - "/cs/student/projects2/aisd/2024/tcannon/dissertation/Dissertation/input_data/lidar_patches_pondinlet"
    - "/cs/student/projects2/aisd/2024/tcannon/dissertation/Dissertation/input_data/lidar_patches_tuk"
  # meters per pixel for LiDAR/residual raster
  pixel_size_m: 1.0

# Training parameters
training:
  batch_size: 8
  epochs: 200
  lr: 0.0001
  timesteps: 1000
  noise_schedule: "linear"
  num_workers: 16
  context_k: 1
  randomize_context: false
  loss:
    name: "masked_mse_loss"  
    alpha: 0.1 

# Model parameters
model:
  unet_depth: 4
  base_channels: 128
  embed_dim: 256
  attention_variant: "default"

# Logging and saving
logging:
  wandb_project: "revised_dissertation"
  wandb_name: null
  run_name: "default_run"
  save_dir: "/cs/student/projects2/aisd/2024/tcannon/dissertation/Dissertation/models"
  output_dir: "/cs/student/projects2/aisd/2024/tcannon/dissertation/Dissertation/reconstructions"

# Sampling and evaluation
evaluation:
  sampling_methods:
    - ddpm
  evaluate: false
  eval_index_json: "fixed_eval.json"
    # multiscale JSD settings
  jsd_scales_m: [1.0, 2.0, 5.0, 10.0]
  jsd_bins: 256
  # normal angle settings
  nae_use_sobel: true
  nae_degrees: true
  # PSD settings
  psd_window: true

# System settings
system:
  device: "auto"
  debug: false